pipeline {
    agent any
    tools {
        jdk 'jdk21' // This name must match the JDK installation name used in Jenkins Global Tool Configuration
    }
    // environment {
    //     DOCKER_PASSWORD = credentials("docker_password")
    // }
    // 
    // 

    environment {
        DOCKER_PASSWORD = credentials("docker_password2")
        GITHUB_TOKEN = credentials("github_token")
    }


    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }
        stage('Tag image') {
            steps {

                withCredentials([usernamePassword(credentialsId: 'docker_password2', usernameVariable: 'USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {

                    script {
                        GIT_TAG = sh([script: 'git fetch --tag && git tag', returnStdout: true]).trim()
                        MAJOR_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 1', returnStdout: true]).trim()
                        MINOR_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 2', returnStdout: true]).trim()
                        PATCH_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 3', returnStdout: true]).trim()
                        sh "docker build -t michael2511/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION} ."
                        sh "echo ${DOCKER_PASSWORD} | docker login docker.io -u michael2511 --password-stdin"
                        sh "docker push michael2511/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION}"

                        sh "git tag ${env.IMAGE_TAG}"
                        sh "git push https://${GITHUB_TOKEN}@github.com/michael2511/service.git ${env.IMAGE_TAG}"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh "IMAGE_TAG=${env.IMAGE_TAG} docker compose up -d hello mongo"
                }
            }
        }
    }

}
